#!/usr/bin/env python

import os
import sys
import json
from pprint import pprint

if os.path.exists(sys.argv[1]):

    with open(sys.argv[1]) as data_file:    
        data = json.load(data_file)

    pprint(data)
