#!/usr/bin/env python

from basic_functions import *

SECTION_SHOW={}
SECTION_SHOW[SECTION_PERSONAL_INFO]=True
SECTION_SHOW[SECTION_OBJECTIVE]=True
SECTION_SHOW[SECTION_EDUCATION]=True
SECTION_SHOW[SECTION_RESEARCH]=True
SECTION_SHOW[SECTION_TEACHING]=True
SECTION_SHOW[SECTION_PRESS]=True
SECTION_SHOW[SECTION_WORK_SKILLS]=True
SECTION_SHOW[SECTION_ACTIVITIES]=True
SECTION_SHOW[SECTION_PUBLICATIONS]=True
SECTION_SHOW[SECTION_AWARDS]=True

#inches
LEFT_RIGHT_MARGIN=1.25
TOP_MARGIN=1
BOTTOM_MARGIN=1
