#!/usr/bin/env python

import os
import sys
import json
from pprint import pprint

#http://stackoverflow.com/questions/14902299/json-loads-allows-duplicate-keys-in-a-dictionary-overwriting-the-first-value
def dict_raise_on_duplicates(ordered_pairs):
    """Reject duplicate keys."""
    d = {}
    for k, v in ordered_pairs:
        if k in d:
           raise ValueError("duplicate key: %r" % (k,))
        else:
           d[k] = v
    return d

if os.path.exists(sys.argv[1]):

    with open(sys.argv[1]) as data_file:    
        data = json.load(data_file,object_pairs_hook=dict_raise_on_duplicates)

    pprint(data)
